### ISSUE TITLE
sticky priority + drain sessions

### ISSUE THREAD

**Issue by cunningwasabi** [yyyar/gobetween#209] opened 2019-03-19 18:17 UTC
hi all, I've updated gobetween to include "sticky" sessions with a priority backend.
in addition to being sticky to a backend, i've updated the discovery mechanism to include a "drainsessions" parameter. drainsessions means that you can administratively force chatty clients off an active backend regardless of idle time.
if you have a backend list of;
10.1.1.1 priority=1
10.1.1.2 priority=2
you can switch discovery to return;
10.1.1.1 priority=2
10.1.1.2 priority=1
but because sessions are sticky, chatty clients can stay on 10.1.1.2 forever.
if you switch discovery to this;
10.1.1.1 priority=2 drainsessions=true
10.1.1.2 priority=1
then any clients on 10.1.1.1 will have sessions removed after the session 'idle timeout' is reached.
importantly, this means the backend can still be kept as 'valid', so it can still be used if 10.1.1.2 fails healthcheck.

**Comment by cunningwasabi** [comment] 2019-03-29 08:33
https://github.com/cunningwasabi/gobetween/tree/StickyPriority

**Comment by illarion** [comment] 2019-03-29 08:47
duplicate of #191

**Closed by illarion** 2019-03-29 08:47 UTC
