### ISSUE TITLE
Which swarm version? / 1.12 have major implications

### ISSUE THREAD

**Issue by pascalandy** [yyyar/gobetween#37] opened 2016-10-03 04:07 UTC
Does this project support 1.12+ ? As there is no mention of it, I guess it's not.

I'm still looking for a solid reverse-proxy under Docker Swarm 1.12+ (using 1.12.1 at the moment). Here some [solutions](Does this project support 1.12+ ? ) meanwhile.

Cheers!

**Comment by nickdoikov** [comment] 2016-10-03 04:14
Hello @pascalandy 

Docker 1.12 family supported as well as docker  [Swarm Standalone](https://github.com/docker/swarm) (not a swarm mode)

**Comment by pascalandy** [comment] 2016-10-03 04:33
Thanks!

**Comment by illarion** [comment] 2016-10-19 18:18
looks like the issue is solved so if no objections, we can close it

**Closed** 2016-10-26 13:33 UTC
