### ISSUE TITLE
udp balance policy "iphash" works not same as expectation

### ISSUE THREAD

**Issue by zhanyonm** [yyyar/gobetween#176] opened 2018-08-29 11:28 UTC
setup a balance :
protocol: udp
balance: iphash

startup multi udp processes in a client host and receive the packets from different backends.
 I understand the same client ip@ should be transferred to same backend. Could you help to check if its behavior is right or my configure is wrong?

this is my configure:
[servers.84aa0fe571ab492882151b2946d7b47c]
bind = "10.212.1.103:5000"
protocol = "udp"

balance = "iphash"

max_connections = 5000
client_idle_timeout = "60s"
backend_idle_timeout = "60s"
backend_connection_timeout = "60s"
[servers.84aa0fe571ab492882151b2946d7b47c.udp] # (optional)
max_requests  = 0     # (optional) if > 0 accepts no more requests than max_requests and closes session (since 0.5.0)
max_responses = 0    # (required) if > 0 accepts no more responses that max_responses from backend and closes session (will be optional since 0.5.0)

    [servers.84aa0fe571ab492882151b2946d7b47c.discovery]
    kind = "static"
    failpolicy = "keeplast"
    static_list = [

      "192.168.48.235:10000",

      "192.168.48.239:10000",

    ]

**Comment by illarion** [comment] 2018-08-29 22:59
You understand the expected behavior right. But I could not reproduce the error locally. How do you check that you're receiving packets from different backends?

**Comment by zhanyonm** [comment] 2018-08-30 03:26
I write client/server scripts, the server scripts run in different backend. then the server will send its ip@ to client when it receives any packets from the clients.
at the client server, the client scripts will output stdout the data received from server.
now I run the multi client scripts at a client host, and the client host display different backend ip@s.

**Comment by illarion** [comment] 2018-09-07 02:13
Are you 100% sure that clients sending udp packets use consistent  routing table? Don't you run it in some managed environment that can adjust routing on the fly?

**Comment by zhanyonm** [comment] 2018-09-07 02:45
@illarion I'm sure it. my testbed is very simple and the route table is configured static.  two clients are in a same network with GB/router directly.
like this:
![image](https://user-images.githubusercontent.com/40659378/45195629-23770100-b28b-11e8-9613-234425f08fc8.png)

**Comment by illarion** [comment] 2018-09-20 12:19
I close it as not reproducable.

**Closed by illarion** 2018-09-20 12:19 UTC

**Comment by nycterent** [comment] 2019-08-05 07:32
I am experiencing similar issue, but I cannot fix it with my limited skills. I have multiple backends and using iphash balance method. My expectations are that all connections coming from specific ip would be sent to the same backend, but I can see that it is not the case (sometimes it works and sometimes does not): 

`2019-08-05 07:22:44 [INFO ] (execFetch): Fetched [{b.b.b.131:4500 p=1,w=1,l=true,a=0} {b.b.b.133:4500 p=1,w=1,l=true,a=0} {b.b.b.135:4500 p=1,w=1,l=true,a=0} {b.b.b.137:4500 p=1,w=1,l=true,a=0} {b.b.b.139:4500 p=1,w=1,l=true,a=0} {b.b.b.141:4500 p=1,w=1,l=true,a=0}]
2019-08-05 07:22:44 [INFO ] (execFetch): Fetched [{b.b.b.131:500 p=1,w=1,l=true,a=0} {b.b.b.133:500 p=1,w=1,l=true,a=0} {b.b.b.135:500 p=1,w=1,l=true,a=0} {b.b.b.137:500 p=1,w=1,l=true,a=0} {b.b.b.139:500 p=1,w=1,l=true,a=0} {b.b.b.141:500 p=1,w=1,l=true,a=0}]
2019-08-05 07:23:11 [DEBUG] (udp/server): Hash key:c.c.c.51:48959
2019-08-05 07:23:11 [DEBUG] (udp/server): Selecting backend: b.b.b.137:500
2019-08-05 07:23:11 [DEBUG] (udp/server): Hash key:c.c.c.51:51167
2019-08-05 07:23:11 [DEBUG] (udp/server): Selecting backend: b.b.b.137:4500
2019-08-05 07:23:11 [DEBUG] (udp/server): Hash key:c.c.c.51:51167
2019-08-05 07:23:11 [DEBUG] (udp/server): Hash key:c.c.c.51:51167
2019-08-05 07:23:11 [DEBUG] (udp/server): Hash key:c.c.c.51:51167
2019-08-05 07:23:11 [DEBUG] (udp/server): Hash key:c.c.c.51:51167
2019-08-05 07:23:12 [DEBUG] (udp/server): Hash key:c.c.c.51:51167
2019-08-05 07:23:12 [DEBUG] (udp/server): Hash key:c.c.c.51:51167
2019-08-05 07:23:12 [DEBUG] (udp/server): Hash key:c.c.c.51:51167
2019-08-05 07:23:12 [DEBUG] (udp/server): Hash key:c.c.c.51:51167
2019-08-05 07:23:12 [DEBUG] (udp/server): Hash key:c.c.c.51:51167
2019-08-05 07:23:12 [DEBUG] (udp/server): Hash key:c.c.c.51:51167
2019-08-05 07:23:12 [DEBUG] (udp/server): Hash key:c.c.c.51:51167
2019-08-05 07:23:12 [DEBUG] (udp/server): Hash key:c.c.c.51:51167
2019-08-05 07:23:13 [DEBUG] (udp/server): Hash key:c.c.c.51:51167
2019-08-05 07:23:24 [DEBUG] (udp/server): Hash key:c.c.c.51:20632
2019-08-05 07:23:24 [DEBUG] (udp/server): Selecting backend: b.b.b.133:500
2019-08-05 07:23:24 [DEBUG] (udp/server): Hash key:c.c.c.51:14903
2019-08-05 07:23:24 [DEBUG] (udp/server): Selecting backend: b.b.b.135:4500
2019-08-05 07:23:28 [DEBUG] (udp/server): Hash key:c.c.c.51:14903`

I am guessing that somewhere outgoing port of the client is used in a hash

Using gobetween_0.8.0+snapshot_linux_amd64
