### ISSUE TITLE
Gobetween not refreshing sni value of LXD container in lxd discovery

### ISSUE THREAD

**Issue by shantanugadgil** [yyyar/gobetween#94] opened 2017-06-14 10:53 UTC
Hi,

I have an LXD container with Minio running inside it.
Gobetween is running on the host (common.example.com) in the scenario explanation below.

The behavior I am observing is that Gobetween is not picking up the **change** in the 'sni value' set in the key 'user.gobetween.sni' (if the value is modified after gobetween has started)

My relevant gobetween config section is:
```
[servers.fe13443]
protocol = "tcp"
bind = ":13443"
sni_enabled = true

[servers.fe13443.discovery]
kind = "lxd"
lxd_server_address = "unix:///var/lib/lxd/unix.socket"
failpolicy = "setempty"
interval = "10s"

lxd_container_label_key = "user.gobetween.label"
lxd_container_label_value = "s3"
lxd_container_port = 9000
lxd_container_sni_key = "user.gobetween.sni"

timeout = "5s"
lxd_generate_client_certs = true
lxd_accept_server_cert = true
lxd_container_address_type = "IPv4"

[servers.fe13443.sni]
enabled = true
read_timeout = "10s"
hostname_matching_strategy = "exact"
unexpected_hostname_strategy = "default"

[servers.fe13443.healthcheck]
kind = "ping"
interval = "60s"
ping_timeout_duration = "5s"
```

Scenario:
- the relevant lxc config section:
```# lxc config show mylxd```

```
config:
  user.gobetween.label: s3
  user.gobetween.sni: s3.example.com
```
  

- Start gobetween with the above config

- connect from remote using the "servername" field as "s3.example.com" (this works)
```# openssl s_client -servername s3.example.com -connect common.example.com:13443```

- change the "sni" value inside the lxd config:
```# lxc config set mylxd user.gobetween.sni s4.example.com```

- wait for 2 mins, connect from remote host using new "servername" field (this doesn't work)
`# openssl s_client -servername s4.example.com -connect common.example.com:13443`

- the following _still_ works
`# openssl s_client -servername s3.example.com -connect common.example.com:13443`

I think the sni field being "advertised" by the LXD container is not being refreshed by Gobetween, because
the previous "servername" still works.

Regards,
Shantanu

**Comment by jtopjian** [comment] 2017-06-15 02:45
Either I'm unable to reproduce this problem or this isn't specific to LXD discovery.

Note that I did not set up a full SNI test to do an end-to-end test. However, I added some debug logging to view the backend being refreshed. I then configured a discovery refresh of 2 seconds:

```
2017-06-15 02:41:12 [DEBUG] (lxdBuildConfig): Using API: unix:///var/lib/lxd/unix.socket
2017-06-15 02:41:12 [DEBUG] (lxdFetch): Fetching containers from unix:///var/lib/lxd/unix.socket
2017-06-15 02:41:12 [INFO ] (lxdFetch): Backends: []core.Backend{core.Backend{Target:core.Target{Host:"10.108.174.177", Port:"80"}, Priority:1, Weight:1, Sni:"foo.bar.com", Stats:core.BackendStats{Live:true, TotalConnections:0, ActiveConnections:0x0, RefusedConnections:0x0, RxBytes:0x0, TxBytes:0x0, RxSecond:0x0, TxSecond:0x0}}}

2017-06-15 02:41:14 [DEBUG] (lxdBuildConfig): Using API: unix:///var/lib/lxd/unix.socket
2017-06-15 02:41:14 [DEBUG] (lxdFetch): Fetching containers from unix:///var/lib/lxd/unix.socket
2017-06-15 02:41:15 [INFO ] (lxdFetch): Backends: []core.Backend{core.Backend{Target:core.Target{Host:"10.108.174.177", Port:"80"}, Priority:1, Weight:1, Sni:"foo.example.com", Stats:core.BackendStats{Live:true, TotalConnections:0, ActiveConnections:0x0, RefusedConnections:0x0, RxBytes:0x0, TxBytes:0x0, RxSecond:0x0, TxSecond:0x0}}}
```

You can see that the backend SNI was successfully updated from `foo.bar.com` to `foo.example.com`. So from what I can see, the container change is propagating into the backend.

**Comment by yyyar** [comment] 2017-06-15 05:46
Yep, LXD Discovery is working correctly. There is a bug with sni update in scheduler, and it's easy to fix.
@shantanugadgil thanks for the issue

**Comment by yyyar** [comment] 2017-06-15 05:48
@shantanugadgil fixed in master, could you please try it again to check if it working correctly now.

**Comment by shantanugadgil** [comment] 2017-06-15 07:13
@yyyar Trying it now. Will confirm soon if it works as expected, thanks!

**Comment by shantanugadgil** [comment] 2017-06-15 11:40
Just confirming that this is working on my test setup.
I change the key `user.gobetween.sni` and teh accept/reject work correctly.

Thanks!

**Closed** 2017-06-15 20:28 UTC
Labels: bug
