### ISSUE TITLE
why put the software inside the src folder?

### ISSUE THREAD

**Issue by avelino** [yyyar/gobetween#130] opened 2018-03-23 12:26 UTC
I understand that the repository gets more organized, but thinking about software standard Go (Gopath pattern) and relative import (ref #87 very important for this project) gets bad to work

I'm not here to **criticize**, I'm willing to help in this refactoring

I do not want to have to create `gofn/dproxy`[1], my idea is uses the **gobetween**, so my willingness to contribute

[1] https://github.com/gofn/dproxy

**Comment by yyyar** [comment] 2018-04-12 23:54
Hi @avelino sorry for a late reply.
Yep the original idea was to keep repo more organized and since it is not a library that is expected to be used in other's code, but rather something that builds to binary executable, we did it as it is.
Could you please describe what exactly you want to achieve: just make gobetween meet Go standard, or also something else?
Thanks!

**Comment by illarion** [comment] 2018-04-16 12:11
Btw it's duplicate of #87

**Comment by avelino** [comment] 2018-04-16 21:04
`gofn/dproxy` will proxy to Docker backend (http and socket)
my idea is to extend the gobetween to my need, creating `gofn/dproxy` using the gobetween (package)

**Closed** 2019-04-10 09:12 UTC
Labels: question
